name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'stable'

    - name: Display Flutter version
      run: flutter --version

    - name: Uninstall previous Dart SDK
      run: sudo rm -rf /usr/lib/dart

    - name: Install Dart SDK 3.0.5
      run: |
        wget https://storage.googleapis.com/dart-archive/channels/stable/release/3.0.5/sdk/dartsdk-linux-x64-release.zip
        unzip -q dartsdk-linux-x64-release.zip -d /usr/lib
        rm dartsdk-linux-x64-release.zip

    - name: Set up environment variables
      run: echo "PATH=/usr/lib/dart/bin:\$PATH" >> $GITHUB_ENV

    - name: Flutter pub get
      run: flutter pub get

    - name: Run tests
      run: flutter test
