name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'stable'

    - name: Display Flutter version
      run: flutter --version

    - name: Set up Dart SDK
      run: |
        echo "Dart SDK version required: >=3.0.5 <4.0.0"
        curl -sSLO https://storage.googleapis.com/dart-archive/channels/stable/release/2.17.0-266.8.beta/sdk/dartsdk-windows-x64-release.zip
        7z x -aoa dartsdk-windows-x64-release.zip -o%USERPROFILE%
        echo "::add-path::%USERPROFILE%\\dart-sdk\\bin"

    - name: Dart pub get
      run: dart pub get

    - name: Flutter pub get
      run: flutter pub get

    - name: Run tests
      run: flutter test
