name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'any'

    - name: Display Flutter version
      run: flutter --version

    - name: Set up Dart SDK
      run: |
        flutter config --no-analytics
        flutter doctor --android-licenses
        flutter upgrade
        flutter pub global activate dart-sdk

    - name: Set up environment variables
      run: echo "PATH=\$PATH:`flutter pub global path`" >> $GITHUB_ENV

    - name: Dart pub get
      run: dart pub get

    - name: Flutter pub get
      run: flutter pub get

    - name: Run tests
      run: flutter test
